package store

import (
	"errors"
	"os"
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
)

// goldenDir holds byte-exact fixtures shared with the fuzz corpus. The
// path is relative because go test runs with the package directory as the
// working directory.
const goldenDir = "../../testdata/format/golden"

// goldenRecords pairs each record type with its exact 64 bytes. The byte
// slices are written out by hand from the layout in docs/format.md, never
// generated by encodeRecord — a round-trip test alone passes for any
// bijective layout, so these literals are what actually pin each field to
// its offset.
var goldenRecords = []struct {
	name string
	file string
	buf  []byte
	rec  Record
}{
	{
		name: "delta",
		file: "record_delta.bin",
		buf: []byte{
			0x08, 0x07, 0x06, 0x05, 0x04, 0x03, 0x02, 0x01, // exchange_ts
			0x18, 0x17, 0x16, 0x15, 0x14, 0x13, 0x12, 0x11, // sequence_number
			0x24, 0x23, 0x22, 0x21, // instrument_id
			0x32, 0x31, // venue_id
			0x00,                                           // record_type
			0x01,                                           // side_flags
			0x48, 0x47, 0x46, 0x45, 0x44, 0x43, 0x42, 0x41, // price
			0x58, 0x57, 0x56, 0x55, 0x54, 0x53, 0x52, 0x51, // size
			0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // blob_offset
			0x00, 0x00, 0x00, 0x00, // blob_len
			0x00, 0x00, // level_count
			0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // reserved
		},
		rec: Record{
			ExchangeTs:     0x0102030405060708,
			SequenceNumber: 0x1112131415161718,
			InstrumentID:   0x21222324,
			VenueID:        0x3132,
			RecordType:     RecordTypeDelta,
			SideFlags:      SideAsk,
			Price:          0x4142434445464748,
			Size:           0x5152535455565758,
		},
	},
	{
		name: "trade_at_field_extremes",
		file: "record_trade.bin",
		buf: []byte{
			0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x7F, // exchange_ts: max int64
			0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, // sequence_number: max uint64
			0xFF, 0xFF, 0xFF, 0xFF, // instrument_id: max uint32
			0xFF, 0xFF, // venue_id: max uint16
			0x01,                                           // record_type
			0x00,                                           // side_flags
			0xFE, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, // price: -2
			0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // size: 1
			0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // blob_offset
			0x00, 0x00, 0x00, 0x00, // blob_len
			0x00, 0x00, // level_count
			0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // reserved
		},
		rec: Record{
			ExchangeTs:     0x7FFFFFFFFFFFFFFF,
			SequenceNumber: 0xFFFFFFFFFFFFFFFF,
			InstrumentID:   0xFFFFFFFF,
			VenueID:        0xFFFF,
			RecordType:     RecordTypeTrade,
			SideFlags:      SideBid,
			Price:          -2,
			Size:           1,
		},
	},
	{
		name: "snapshot_pointer",
		file: "record_snapshot_pointer.bin",
		buf: []byte{
			0x11, 0x10, 0x0F, 0x0E, 0x0D, 0x0C, 0x0B, 0x0A, // exchange_ts
			0x27, 0x26, 0x25, 0x24, 0x23, 0x22, 0x21, 0x20, // sequence_number
			0x34, 0x33, 0x32, 0x31, // instrument_id
			0x42, 0x41, // venue_id
			0x02,                                           // record_type
			0x00,                                           // side_flags
			0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // price
			0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // size
			0x00, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // blob_offset: 4096
			0x38, 0x00, 0x00, 0x00, // blob_len: 8 + 16*3
			0x03, 0x00, // level_count: 3
			0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // reserved
		},
		rec: Record{
			ExchangeTs:     0x0A0B0C0D0E0F1011,
			SequenceNumber: 0x2021222324252627,
			InstrumentID:   0x31323334,
			VenueID:        0x4142,
			RecordType:     RecordTypeSnapshotPointer,
			BlobOffset:     4096,
			BlobLen:        blobHeaderSize + 3*levelSize,
			LevelCount:     3,
		},
	},
}

func TestRecordGolden(t *testing.T) {
	for _, g := range goldenRecords {
		t.Run(g.name+"_decodes_to_the_expected_record", func(t *testing.T) {
			got, err := decodeRecord(g.buf)

			if err != nil {
				t.Fatalf("decodeRecord() error = %v, want nil", err)
			}
			if diff := cmp.Diff(g.rec, got); diff != "" {
				t.Errorf("decodeRecord() mismatch (-want +got):\n%s", diff)
			}
		})

		t.Run(g.name+"_encodes_to_the_expected_bytes", func(t *testing.T) {
			var buf [RecordSize]byte
			// Prefill with a non-zero pattern: encodeRecord must write
			// every byte, including the reserved range.
			for i := range buf {
				buf[i] = 0xAB
			}

			encodeRecord(buf[:], g.rec)

			if diff := cmp.Diff(g.buf, buf[:]); diff != "" {
				t.Errorf("encodeRecord() mismatch (-want +got):\n%s", diff)
			}
		})

		t.Run(g.name+"_committed_file_matches_the_literal", func(t *testing.T) {
			got, err := os.ReadFile(filepath.Join(goldenDir, g.file))

			if err != nil {
				t.Fatalf("reading golden file: %v", err)
			}
			if diff := cmp.Diff(g.buf, got); diff != "" {
				t.Errorf("%s mismatch (-literal +file):\n%s", g.file, diff)
			}
		})
	}
}

func TestDecodeRecordRejects(t *testing.T) {
	// Each case mutates the valid delta golden at one offset.
	delta := goldenRecords[0].buf

	tests := []struct {
		name string
		mut  func(b []byte)
		want error
	}{
		{
			name: "unknown_record_type",
			mut:  func(b []byte) { b[offRecordType] = recordTypeCount },
			want: ErrRecordType,
		},
		{
			name: "side_flags_reserved_bit_set",
			mut:  func(b []byte) { b[offSideFlags] = 0x02 },
			want: ErrSideFlags,
		},
		{
			name: "reserved_byte_set",
			mut:  func(b []byte) { b[offReserved+lenReserved-1] = 0x01 },
			want: ErrReserved,
		},
		{
			name: "blob_offset_set_on_a_delta",
			mut:  func(b []byte) { b[offBlobOffset] = 0x01 },
			want: ErrUnusedFieldSet,
		},
		{
			name: "level_count_set_on_a_delta",
			mut:  func(b []byte) { b[offLevelCount] = 0x01 },
			want: ErrUnusedFieldSet,
		},
		{
			name: "price_set_on_a_snapshot_pointer",
			mut: func(b []byte) {
				copy(b, goldenRecords[2].buf)
				b[offPrice] = 0x01
			},
			want: ErrUnusedFieldSet,
		},
		{
			name: "blob_len_shorter_than_the_blob_header",
			mut: func(b []byte) {
				copy(b, goldenRecords[2].buf)
				b[offBlobLen] = blobHeaderSize - 1
			},
			want: ErrBlobLen,
		},
		{
			name: "blob_len_not_a_whole_number_of_levels",
			mut: func(b []byte) {
				copy(b, goldenRecords[2].buf)
				b[offBlobLen] = blobHeaderSize + levelSize + 1
			},
			want: ErrBlobLen,
		},
		{
			name: "level_count_disagrees_with_blob_len",
			mut: func(b []byte) {
				copy(b, goldenRecords[2].buf)
				b[offLevelCount] = 4
			},
			want: ErrBlobLen,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			buf := make([]byte, RecordSize)
			copy(buf, delta)
			tt.mut(buf)

			_, err := decodeRecord(buf)

			if !errors.Is(err, tt.want) {
				t.Errorf("decodeRecord() error = %v, want %v", err, tt.want)
			}
		})
	}

	t.Run("buffer_shorter_than_one_record", func(t *testing.T) {
		_, err := decodeRecord(delta[:RecordSize-1])

		if !errors.Is(err, ErrShortRecord) {
			t.Errorf("decodeRecord() error = %v, want %v", err, ErrShortRecord)
		}
	})
}

func TestRecordRoundTrip(t *testing.T) {
	for _, g := range goldenRecords {
		t.Run(g.name, func(t *testing.T) {
			var buf [RecordSize]byte

			encodeRecord(buf[:], g.rec)
			got, err := decodeRecord(buf[:])

			if err != nil {
				t.Fatalf("decodeRecord() error = %v, want nil", err)
			}
			if diff := cmp.Diff(g.rec, got); diff != "" {
				t.Errorf("round trip mismatch (-want +got):\n%s", diff)
			}
		})
	}
}
