// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: replay.proto

// Package replay is the wire schema cmd/replayd serves.
//
// There is no map<> field anywhere in this file, and there must never
// be one. Protobuf leaves map field marshaling order undefined, so a map
// would put nondeterminism back at the one boundary that looks like "a
// message definition" rather than "code". Where a map would be the
// obvious shape, use a repeated field in an order this schema states.

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mode is the backpressure mode, explicit at subscribe time. The zero
// value names neither Block nor Drop and the server rejects it: a
// default that silently picks one is exactly what this project's
// backpressure invariant forbids, and proto3's implicit-zero field
// presence means an unset field is indistinguishable from MODE_BLOCK if
// MODE_BLOCK were zero. See docs/backpressure.md.
type Mode int32

const (
	Mode_MODE_UNSPECIFIED Mode = 0
	Mode_MODE_BLOCK       Mode = 1
	Mode_MODE_DROP        Mode = 2
)

// Enum value maps for Mode.
var (
	Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "MODE_BLOCK",
		2: "MODE_DROP",
	}
	Mode_value = map[string]int32{
		"MODE_UNSPECIFIED": 0,
		"MODE_BLOCK":       1,
		"MODE_DROP":        2,
	}
)

func (x Mode) Enum() *Mode {
	p := new(Mode)
	*p = x
	return p
}

func (x Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_replay_proto_enumTypes[0].Descriptor()
}

func (Mode) Type() protoreflect.EnumType {
	return &file_replay_proto_enumTypes[0]
}

func (x Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mode.Descriptor instead.
func (Mode) EnumDescriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{0}
}

// StartAtBeginning selects the first record the ring still holds. It
// carries no data: a start position with no parameter is still its own
// oneof case, which is what keeps "which start kind" explicit on the
// wire instead of inferred from a zero value.
type StartAtBeginning struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAtBeginning) Reset() {
	*x = StartAtBeginning{}
	mi := &file_replay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAtBeginning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAtBeginning) ProtoMessage() {}

func (x *StartAtBeginning) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAtBeginning.ProtoReflect.Descriptor instead.
func (*StartAtBeginning) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{0}
}

// StartAtLive selects whatever the write index is when the subscription
// is registered. It is the one start position this project does not
// claim is reproducible.
type StartAtLive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAtLive) Reset() {
	*x = StartAtLive{}
	mi := &file_replay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAtLive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAtLive) ProtoMessage() {}

func (x *StartAtLive) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAtLive.ProtoReflect.Descriptor instead.
func (*StartAtLive) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{1}
}

// SubscribeRequest opens one subscription.
type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// mode must be MODE_BLOCK or MODE_DROP.
	Mode Mode `protobuf:"varint,1,opt,name=mode,proto3,enum=replay.Mode" json:"mode,omitempty"`
	// start must be set. The four cases mirror internal/fanout's four
	// StartAt constructors exactly.
	//
	// Types that are valid to be assigned to Start:
	//
	//	*SubscribeRequest_Beginning
	//	*SubscribeRequest_ExchangeTs
	//	*SubscribeRequest_EmitIndex
	//	*SubscribeRequest_Live
	Start isSubscribeRequest_Start `protobuf_oneof:"start"`
	// speed_num / speed_den is the replay speed as an exact rational:
	// 1/1 is real time, 10000/1 is ten thousand times real time. It is
	// two int64 fields and never a double, for the reason internal/fanout
	// .Speed exists at all — Go fuses floating-point multiply-add on some
	// architectures and not others, so the same double could schedule a
	// record differently on two machines, and pacing decides when a Drop
	// subscriber is lapped. There is no float anywhere in this schema.
	// See docs/clock.md.
	SpeedNum      int64 `protobuf:"varint,6,opt,name=speed_num,json=speedNum,proto3" json:"speed_num,omitempty"`
	SpeedDen      int64 `protobuf:"varint,7,opt,name=speed_den,json=speedDen,proto3" json:"speed_den,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_replay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetMode() Mode {
	if x != nil {
		return x.Mode
	}
	return Mode_MODE_UNSPECIFIED
}

func (x *SubscribeRequest) GetStart() isSubscribeRequest_Start {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *SubscribeRequest) GetBeginning() *StartAtBeginning {
	if x != nil {
		if x, ok := x.Start.(*SubscribeRequest_Beginning); ok {
			return x.Beginning
		}
	}
	return nil
}

func (x *SubscribeRequest) GetExchangeTs() int64 {
	if x != nil {
		if x, ok := x.Start.(*SubscribeRequest_ExchangeTs); ok {
			return x.ExchangeTs
		}
	}
	return 0
}

func (x *SubscribeRequest) GetEmitIndex() uint64 {
	if x != nil {
		if x, ok := x.Start.(*SubscribeRequest_EmitIndex); ok {
			return x.EmitIndex
		}
	}
	return 0
}

func (x *SubscribeRequest) GetLive() *StartAtLive {
	if x != nil {
		if x, ok := x.Start.(*SubscribeRequest_Live); ok {
			return x.Live
		}
	}
	return nil
}

func (x *SubscribeRequest) GetSpeedNum() int64 {
	if x != nil {
		return x.SpeedNum
	}
	return 0
}

func (x *SubscribeRequest) GetSpeedDen() int64 {
	if x != nil {
		return x.SpeedDen
	}
	return 0
}

type isSubscribeRequest_Start interface {
	isSubscribeRequest_Start()
}

type SubscribeRequest_Beginning struct {
	Beginning *StartAtBeginning `protobuf:"bytes,2,opt,name=beginning,proto3,oneof"`
}

type SubscribeRequest_ExchangeTs struct {
	ExchangeTs int64 `protobuf:"varint,3,opt,name=exchange_ts,json=exchangeTs,proto3,oneof"`
}

type SubscribeRequest_EmitIndex struct {
	EmitIndex uint64 `protobuf:"varint,4,opt,name=emit_index,json=emitIndex,proto3,oneof"`
}

type SubscribeRequest_Live struct {
	Live *StartAtLive `protobuf:"bytes,5,opt,name=live,proto3,oneof"`
}

func (*SubscribeRequest_Beginning) isSubscribeRequest_Start() {}

func (*SubscribeRequest_ExchangeTs) isSubscribeRequest_Start() {}

func (*SubscribeRequest_EmitIndex) isSubscribeRequest_Start() {}

func (*SubscribeRequest_Live) isSubscribeRequest_Start() {}

// Level is one price level of a snapshot. Price and size are scaled
// integers, never floats: a double can be NaN, which is not equal to
// itself and breaks both the comparator and the hash.
type Level struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         int64                  `protobuf:"varint,1,opt,name=price,proto3" json:"price,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Level) Reset() {
	*x = Level{}
	mi := &file_replay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Level) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Level) ProtoMessage() {}

func (x *Level) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Level.ProtoReflect.Descriptor instead.
func (*Level) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{3}
}

func (x *Level) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Level) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// Record is one replayed event, projected field by field. The numeric
// widths are proto3's, wider than the format's own: venue_id,
// record_type, side_flags and level_count are a uint16, two bytes and a
// uint16 on disk. The values are the format's own, unchanged, so a
// client can rebuild the canonical projection from this message alone.
// See docs/format.md.
type Record struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExchangeTs     int64                  `protobuf:"varint,1,opt,name=exchange_ts,json=exchangeTs,proto3" json:"exchange_ts,omitempty"`
	SequenceNumber uint64                 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	InstrumentId   uint32                 `protobuf:"varint,3,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	VenueId        uint32                 `protobuf:"varint,4,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	RecordType     uint32                 `protobuf:"varint,5,opt,name=record_type,json=recordType,proto3" json:"record_type,omitempty"`
	SideFlags      uint32                 `protobuf:"varint,6,opt,name=side_flags,json=sideFlags,proto3" json:"side_flags,omitempty"`
	Price          int64                  `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	Size           int64                  `protobuf:"varint,8,opt,name=size,proto3" json:"size,omitempty"`
	// level_count, levels and bid_count are set only for a snapshot
	// pointer. levels holds every level already decoded, bids first and
	// then asks, in the order the snapshot stores them — never the raw
	// blob bytes, which would nest this project's private binary format
	// inside its public schema and leave every client to parse it.
	LevelCount    uint32   `protobuf:"varint,9,opt,name=level_count,json=levelCount,proto3" json:"level_count,omitempty"`
	Levels        []*Level `protobuf:"bytes,10,rep,name=levels,proto3" json:"levels,omitempty"`
	BidCount      uint32   `protobuf:"varint,11,opt,name=bid_count,json=bidCount,proto3" json:"bid_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_replay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{4}
}

func (x *Record) GetExchangeTs() int64 {
	if x != nil {
		return x.ExchangeTs
	}
	return 0
}

func (x *Record) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *Record) GetInstrumentId() uint32 {
	if x != nil {
		return x.InstrumentId
	}
	return 0
}

func (x *Record) GetVenueId() uint32 {
	if x != nil {
		return x.VenueId
	}
	return 0
}

func (x *Record) GetRecordType() uint32 {
	if x != nil {
		return x.RecordType
	}
	return 0
}

func (x *Record) GetSideFlags() uint32 {
	if x != nil {
		return x.SideFlags
	}
	return 0
}

func (x *Record) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Record) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Record) GetLevelCount() uint32 {
	if x != nil {
		return x.LevelCount
	}
	return 0
}

func (x *Record) GetLevels() []*Level {
	if x != nil {
		return x.Levels
	}
	return nil
}

func (x *Record) GetBidCount() uint32 {
	if x != nil {
		return x.BidCount
	}
	return 0
}

// SubscribeResponse is one delivery: a record, and the gap that
// immediately preceded it when the writer had already lapped this
// subscriber. One response per delivery, mirroring
// internal/fanout.Delivery.
type SubscribeResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Record *Record                `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	// has_gap says whether the three fields below mean anything. The gap
	// unit is the run's global emit index, never a venue sequence number:
	// a gap in a merged multi-venue stream spans several venues and has
	// no single sequence range that describes it. missed_count is always
	// last_missed_index - first_missed_index + 1. A gap is delivery
	// framing and is never part of the canonical hash. See
	// docs/backpressure.md.
	HasGap           bool   `protobuf:"varint,2,opt,name=has_gap,json=hasGap,proto3" json:"has_gap,omitempty"`
	FirstMissedIndex uint64 `protobuf:"varint,3,opt,name=first_missed_index,json=firstMissedIndex,proto3" json:"first_missed_index,omitempty"`
	LastMissedIndex  uint64 `protobuf:"varint,4,opt,name=last_missed_index,json=lastMissedIndex,proto3" json:"last_missed_index,omitempty"`
	MissedCount      uint64 `protobuf:"varint,5,opt,name=missed_count,json=missedCount,proto3" json:"missed_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_replay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeResponse) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *SubscribeResponse) GetHasGap() bool {
	if x != nil {
		return x.HasGap
	}
	return false
}

func (x *SubscribeResponse) GetFirstMissedIndex() uint64 {
	if x != nil {
		return x.FirstMissedIndex
	}
	return 0
}

func (x *SubscribeResponse) GetLastMissedIndex() uint64 {
	if x != nil {
		return x.LastMissedIndex
	}
	return 0
}

func (x *SubscribeResponse) GetMissedCount() uint64 {
	if x != nil {
		return x.MissedCount
	}
	return 0
}

var File_replay_proto protoreflect.FileDescriptor

const file_replay_proto_rawDesc = "" +
	"\n" +
	"\freplay.proto\x12\x06replay\"\x12\n" +
	"\x10StartAtBeginning\"\r\n" +
	"\vStartAtLive\"\xa0\x02\n" +
	"\x10SubscribeRequest\x12 \n" +
	"\x04mode\x18\x01 \x01(\x0e2\f.replay.ModeR\x04mode\x128\n" +
	"\tbeginning\x18\x02 \x01(\v2\x18.replay.StartAtBeginningH\x00R\tbeginning\x12!\n" +
	"\vexchange_ts\x18\x03 \x01(\x03H\x00R\n" +
	"exchangeTs\x12\x1f\n" +
	"\n" +
	"emit_index\x18\x04 \x01(\x04H\x00R\temitIndex\x12)\n" +
	"\x04live\x18\x05 \x01(\v2\x13.replay.StartAtLiveH\x00R\x04live\x12\x1b\n" +
	"\tspeed_num\x18\x06 \x01(\x03R\bspeedNum\x12\x1b\n" +
	"\tspeed_den\x18\a \x01(\x03R\bspeedDenB\a\n" +
	"\x05start\"1\n" +
	"\x05Level\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x03R\x05price\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"\xe1\x02\n" +
	"\x06Record\x12\x1f\n" +
	"\vexchange_ts\x18\x01 \x01(\x03R\n" +
	"exchangeTs\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x04R\x0esequenceNumber\x12#\n" +
	"\rinstrument_id\x18\x03 \x01(\rR\finstrumentId\x12\x19\n" +
	"\bvenue_id\x18\x04 \x01(\rR\avenueId\x12\x1f\n" +
	"\vrecord_type\x18\x05 \x01(\rR\n" +
	"recordType\x12\x1d\n" +
	"\n" +
	"side_flags\x18\x06 \x01(\rR\tsideFlags\x12\x14\n" +
	"\x05price\x18\a \x01(\x03R\x05price\x12\x12\n" +
	"\x04size\x18\b \x01(\x03R\x04size\x12\x1f\n" +
	"\vlevel_count\x18\t \x01(\rR\n" +
	"levelCount\x12%\n" +
	"\x06levels\x18\n" +
	" \x03(\v2\r.replay.LevelR\x06levels\x12\x1b\n" +
	"\tbid_count\x18\v \x01(\rR\bbidCount\"\xd1\x01\n" +
	"\x11SubscribeResponse\x12&\n" +
	"\x06record\x18\x01 \x01(\v2\x0e.replay.RecordR\x06record\x12\x17\n" +
	"\ahas_gap\x18\x02 \x01(\bR\x06hasGap\x12,\n" +
	"\x12first_missed_index\x18\x03 \x01(\x04R\x10firstMissedIndex\x12*\n" +
	"\x11last_missed_index\x18\x04 \x01(\x04R\x0flastMissedIndex\x12!\n" +
	"\fmissed_count\x18\x05 \x01(\x04R\vmissedCount*;\n" +
	"\x04Mode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"MODE_BLOCK\x10\x01\x12\r\n" +
	"\tMODE_DROP\x10\x022S\n" +
	"\rReplayService\x12B\n" +
	"\tSubscribe\x12\x18.replay.SubscribeRequest\x1a\x19.replay.SubscribeResponse0\x01B\x10Z\x0ereplay/api;apib\x06proto3"

var (
	file_replay_proto_rawDescOnce sync.Once
	file_replay_proto_rawDescData []byte
)

func file_replay_proto_rawDescGZIP() []byte {
	file_replay_proto_rawDescOnce.Do(func() {
		file_replay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_replay_proto_rawDesc), len(file_replay_proto_rawDesc)))
	})
	return file_replay_proto_rawDescData
}

var file_replay_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_replay_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_replay_proto_goTypes = []any{
	(Mode)(0),                 // 0: replay.Mode
	(*StartAtBeginning)(nil),  // 1: replay.StartAtBeginning
	(*StartAtLive)(nil),       // 2: replay.StartAtLive
	(*SubscribeRequest)(nil),  // 3: replay.SubscribeRequest
	(*Level)(nil),             // 4: replay.Level
	(*Record)(nil),            // 5: replay.Record
	(*SubscribeResponse)(nil), // 6: replay.SubscribeResponse
}
var file_replay_proto_depIdxs = []int32{
	0, // 0: replay.SubscribeRequest.mode:type_name -> replay.Mode
	1, // 1: replay.SubscribeRequest.beginning:type_name -> replay.StartAtBeginning
	2, // 2: replay.SubscribeRequest.live:type_name -> replay.StartAtLive
	4, // 3: replay.Record.levels:type_name -> replay.Level
	5, // 4: replay.SubscribeResponse.record:type_name -> replay.Record
	3, // 5: replay.ReplayService.Subscribe:input_type -> replay.SubscribeRequest
	6, // 6: replay.ReplayService.Subscribe:output_type -> replay.SubscribeResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_replay_proto_init() }
func file_replay_proto_init() {
	if File_replay_proto != nil {
		return
	}
	file_replay_proto_msgTypes[2].OneofWrappers = []any{
		(*SubscribeRequest_Beginning)(nil),
		(*SubscribeRequest_ExchangeTs)(nil),
		(*SubscribeRequest_EmitIndex)(nil),
		(*SubscribeRequest_Live)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_replay_proto_rawDesc), len(file_replay_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_replay_proto_goTypes,
		DependencyIndexes: file_replay_proto_depIdxs,
		EnumInfos:         file_replay_proto_enumTypes,
		MessageInfos:      file_replay_proto_msgTypes,
	}.Build()
	File_replay_proto = out.File
	file_replay_proto_goTypes = nil
	file_replay_proto_depIdxs = nil
}
